name: Setup chartmuseum
description: 'Install chartmuseum'
branding:
  icon: 'package'
  color: 'blue'
author: Marco Franssen
inputs:
  chartmuseum-version:
    description: >-
      The chartmuseum version you want to use.
    required: false
    default: v0.15.0
outputs:
  chartmuseum-version:
    description: 'The chartmuseum version that was installed.'
runs:
  using: 'node16'
  main: 'dist/index.js'
