name: Test setup-chartmuseum
on:
  push:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  check-dist:
    name: Check dist
    runs-on: ubuntu-22.04

    permissions:
      contents: read

    steps:
      - name: Check out code
        uses: actions/checkout@v3.1.0

      - name: Setup Node
        uses: actions/setup-node@v3.5.1
        with:
          node-version: '16'

      - name: Setup yarn
        run: npm install --location=global yarn

      - name: Install dependencies
        run: yarn install

      - name: Check diff is up to date
        run: |
          yarn build
          git diff --quiet -- dist || {
            echo "::error::The ./dist is outdated, run 'yarn build' and commit"
            exit 1
          }

  test:
    name: Use setup-chartmuseum

    strategy:
      fail-fast: true
      matrix:
        os: [ubuntu-22.04]
        version:
          - v0.14.0
          - v0.15.0

    runs-on: ${{ matrix.os }}

    needs: [check-dist]

    permissions:
      contents: read

    steps:
      - name: Check out code
        uses: actions/checkout@v3.2.0

      - name: Setup Node
        uses: actions/setup-node@v3.5.1
        with:
          node-version: '16'

      - name: Setup chartmuseum
        id: setup-chartmuseum
        uses: ./
        with:
          chartmuseumVersion: ${{ matrix.version }}

      - name: Check output and installPath
        run: |
          hash chartmuseum 2>/dev/null || { echo >&2 "chartmuseum can not be found in the PATH."; exit 1; }
          echo "::notice::Installed chartmuseum ${chartmuseum_VERSION} at $(which chartmuseum)"
        env:
          chartmuseum_VERSION: ${{ steps.setup-chartmuseum.outputs.chartmuseum-version }}
