name: Test setup-chartmuseum
on:
  push:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  check-dist:
    name: Check dist
    runs-on: ubuntu-22.04

    permissions:
      contents: read

    steps:
      - name: Check out code
        uses: actions/checkout@v3.5.3

      - name: Setup Node
        uses: actions/setup-node@v3.6.0
        with:
          node-version: '16'

      - name: Setup yarn
        run: npm install --location=global yarn

      - name: Install dependencies
        run: yarn install

      - name: Check diff is up to date
        run: |
          yarn build
          git diff --quiet -- dist || {
            echo "::error::The ./dist is outdated, run 'yarn build' and commit"
            exit 1
          }

  test:
    name: Use setup-chartmuseum

    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-22.04
          - macos-12
        version:
          - v0.14.0
          - v0.15.0
        bootup:
          - true
          - false

    runs-on: ${{ matrix.os }}

    needs: [check-dist]

    permissions:
      contents: read

    steps:
      - name: Check out code
        uses: actions/checkout@v3.5.3

      - name: Setup Node
        uses: actions/setup-node@v3.6.0
        with:
          node-version: '16'

      - name: Setup chartmuseum
        id: setup-chartmuseum
        uses: ./
        with:
          chartmuseum-version: ${{ matrix.version }}
          bootup: ${{ matrix.bootup }}

      - name: Check output and installPath
        run: |
          hash chartmuseum 2>/dev/null || { echo >&2 "chartmuseum can not be found in the PATH."; exit 1; }
          echo "::notice::Installed chartmuseum ${chartmuseum_VERSION} at $(which chartmuseum)"
          echo "::notice::Chartmuseum runs at ${chartmuseum_endpoint} "
        env:
          chartmuseum_VERSION: ${{ steps.setup-chartmuseum.outputs.chartmuseum-version }}
          chartmuseum_endpoint: ${{ steps.setup-chartmuseum.outputs.chartmuseum-endpoint }}

      - name: Check chartmuseum is running and reachable
        if: matrix.bootup
        run: |
          ps aux | grep chartmuseum
          curl -v ${chartmuseum_endpoint}
        env:
          chartmuseum_endpoint: ${{ steps.setup-chartmuseum.outputs.chartmuseum-endpoint }}
